apiVersion: v1
kind: Service
metadata:
  name: galera-mariadb
  labels:
    app: galera-mariadb
spec:
  ports:
  - port: 3306
    name: mysql
  clusterIP: None
  selector:
    app: galera-mariadb
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-password
type: Opaque
data:
  # Root password (base64): echo -n 'opcellent' | base64
  password: b3BjZWxsZW50
---

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: galera-mariadb
spec:
  serviceName: "galera-mariadb"
  replicas: 3
  template:
    metadata:
      labels:
        app: galera-mariadb
    spec:
      containers:
      - name: galera-mariadb
        image: labdocker/galara-mariadb:10.1
        ports:
        - name: mysql
          containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-password
              key: password
        - name: DISCOVERY_SERVICE
          value: etcd-client:2379
        - name: XTRABACKUP_PASSWORD
          value: password
        - name: CLUSTER_NAME
          value: galera-mariadb-cluster
 #       - name: MYSQL_DATABASE
 #         value: mydatabase
 #       - name: MYSQL_USER
 #         value: myuser
 #       - name: MYSQL_PASSWORD
 #         value: myuserpassword
        readinessProbe:
          exec:
            command:
            - /healthcheck.sh
            - --readiness
          initialDelaySeconds: 180
          periodSeconds: 1
        livenessProbe:
          exec:
            command:
            - /healthcheck.sh
            - --liveness
          initialDelaySeconds: 210
          periodSeconds: 1
        volumeMounts:
        - name: mysql-datadir
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: glusterfs-heketi
      resources:
        requests:
          storage: 10Gi