apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: gluster-pvc
   annotations:
      volume.beta.kubernetes.io/storage-class: glusterfs-heketi
spec:
   accessModes:
      - ReadWriteOnce
   resources:
      requests:
         storage: 5Gi