kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
   name: glusterfs-heketi
   annotations: 
      storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/glusterfs
parameters:
   resturl: "http://<cluster ip of heketi>:8080"
   restauthenabled: "false"
   volumetype: "replicate:3"